# Generated by Django 4.1.7 on 2023-04-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
                ("descr_prod", models.CharField(max_length=255, null=True)),
                ("quantidate", models.IntegerField()),
                ("data_entrada", models.DateField()),
                ("data_validade", models.DateField()),
                ("lote", models.IntegerField()),
            ],
            options={
                "db_table": "produtos",
            },
        ),
    ]
