# Generated by Django 4.1.7 on 2023-04-25 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produto",
            old_name="quantidate",
            new_name="quantidade",
        ),
    ]
