# Generated by Django 4.1.7 on 2023-04-25 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0002_rename_quantidate_produto_quantidade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produto",
            old_name="id",
            new_name="id_produto",
        ),
    ]
